---
# Variables from Tower Survey:
# visitor_fullname
# visitor_company
# visitor_email
# Location options: sc-akl / sc-wtn / sc-chch / golfday
- name: Photobooth - Capture Photo
  hosts: localhost
  gather_facts: no

  vars:
    - mpjeg_url: "http://192.168.1.245:8008"
    - showcase_home: "/home/feliz/showcase"

  tasks:
  # Playback counting down video
  - name: playback countdown
    become: yes
    become_method: su
    become_user: feliz
    shell: "export DISPLAY=:0; /usr/bin/vlc {{ showcase_home }}/countdown.mp4"
  - name: wait for countdown
    wait_for: timeout=6
  - name: play shutter sound
    become: yes
    become_method: su
    become_user: feliz  
    shell: "export DISPLAY=:0; /usr/bin/vlc {{ showcase_home }}/shutter.aiff"    

  # Capture jpeg from camera (mjpeg stream)
  - name: capture jpeg
    shell: "ffmpeg -i {{ mpjeg_url }} -frames 1 -q:v 1 {{ showcase_home }}/output.jpg -y"

  # Generate unique id for visitor entry
  - name: generate unique id
    shell: "{{ showcase_home }}/unique_id.sh {{ visitor_fullname }}"
    register: uniqueid


- name: Photobooth - Upload Photo to Cloud WebServer
  hosts: showcase-webserver-01
  gather_facts: no

  vars:
    - photowebpath: "/var/www/html/photo/{{ location }}"
    - showcase_home: "/home/feliz/showcase"

  tasks:
  # Upload photo to the cloud webserver
  - name: upload photo to webserver
    copy:
      src: "{{ showcase_home }}/output.jpg"
      dest: "{{ photowebpath }}/{{ uniqueid.stdout_lines[0] }}.jpg"
      mode: u=rw,g=r,o=r


- name: Photobooth - Create Database Entry on DBServer
  hosts: showcase-dbserver
  gather_facts: no

  tasks:
  # Create database entry for visitor
  - name: create an sql file from template
    template:
      src: templates/insert_table.sql.j2
      dest: /tmp/insert_table.sql

  - name: insert database entries
    mysql_db:
      name: showcase
      login_user: ansible
      login_password: redhat
      login_unix_socket: "/var/lib/mysql/mysql.sock"
      config_file: "/etc/my.cnf"      
      state: import
      target: /tmp/insert_table.sql

  - name: test table output
    command: 'mysql -uansible -predhat showcase -e "select * from visitor;"'
    register: tableoutput
  - name: display table output
    debug:
      var: tableoutput.stdout_lines


- name: Photobooth - Printing Flyer
  hosts: localhost
  gather_facts: no

  tasks:
  # Printing Flyer
  - name: printing flyer
    shell: "firefox --headless --new-instance --screenshot printout.png http://{{ public_ip }}/flyer/{{ uniqueid.stdout_lines[0] }}"
    delegate_to: localhost

  # Shows Unique ID
  - name: display photobooth unique id
    debug:
      msg: new unique id is {{ uniqueid.stdout_lines[0] }}
    delegate_to: localhost
...