- name: Photobooth - Printing Flyer
  hosts: localhost
  gather_facts: no

  vars:
    #- webserver_public_ip: "{{ hostvars['showcase-webserver-01']['public_ip'] }}"
    - webserver_public_ip: "www.redhatnz.com"
    - unique_id: "{{ lookup('file', '/tmp/new_unique_id.txt') }}"
    - printoutpath: "/home/feliz/showcase/printout.png"
    - printer_name: "L310"
  
  tasks:
  - name: preparing flyer
    shell: "firefox --headless --new-instance --screenshot {{ printoutpath }} http://{{ webserver_public_ip }}/flyer/{{ unique_id }}"

  - name: print flyer
    shell: "lpr -P {{ printer_name }} {{ printoutpath }}"
...