---
- name: Deploy New Website Application Parts to Webserver
  hosts: showcase-webserver-01
  gather_facts: no
  become: yes
  become_method: sudo

  tasks:
  - name: clear application directory
    file: 
      path: "/var/www/html/application"
      state: "{{ item }}"
    with_items:
      - absent
      - directory

  - name: update website files - application parts
    copy:
      src: "websource/application"
      dest: "/var/www/html/"
      mode: u=rw,g=r,o=r
...