---
- name: Download the latest copy of website source codes
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: get the latest webpage source from git
    git:
      repo: "https://github.com/felizkk/showcase-photobooth.git"
      dest: "/tmp/websource"

- name: Deploy New Website to Webservers
  hosts: showcase-webserver-01
  gather_facts: no
  become: yes
  become_method: sudo
  
  vars:
    - dbserver_ip_address: "10.0.0.5"

  tasks:
  - name: update dns resolve entries on server
    lineinfile:
      path: /etc/hosts
      regexp: dbserver1
      line: "{{ dbserver_ip_address }} dbserver1"
      state: present

  - name: clear application directory
    file: 
      path: "/var/www/html/application"
      state: "{{ item }}"
    with_items:
      - absent
      - directory

  - name: create application directory
    file: 
      path: "/var/www/html/application"
      state: "{{ item }}"
    with_items:
      - present
      - directory      

  - name: update website files - application parts
    copy:
      src: "/tmp/websource/application/"
      dest: "/var/www/html/application/"
      mode: u=rw,g=r,o=r
...