---
- name: Deploy New Website to Webservers
  hosts: showcase-webserver-01
  gather_facts: no
  become: yes
  become_method: sudo
    
  vars:
    - dbserver_ip_address: "10.0.0.5"

  tasks:
  - name: update dns resolve entries on server
    lineinfile:
      path: /etc/hosts
      regexp: dbserver1
      line: "{{ dbserver_ip_address }} dbserver1"
      state: present

  - name: clear html directory
    file: 
      path: /var/www/html
      state: "{{ item }}"
    with_items:
      - absent
      - directory

  - name: update website files
    copy:
      src: websource
      dest: "/var/www/html"
      mode: u=rw,g=r,o=r
...