---
- name: Deploy New Website to Webservers
  hosts: showcase-webserver-01
  gather_facts: no
  become: yes
  become_method: sudo
    
  vars:
    - dbserver_ip_address: "10.0.0.5"

  tasks:
  - name: update dns resolve entries on server
    lineinfile:
      path: /etc/hosts
      regexp: dbserver1
      line: "{{ dbserver_ip_address }} dbserver1"
      state: present

  - name: clear html directory
    file: 
      path: /var/www/html
      state: "{{ item }}"
    with_items:
      - absent
      - directory

  - name: update index php file
    template:
      src: "templates/index.php.j2"
      dest: "/var/www/html/index.php"

  - name: copy the rest of html files
    copy:
      src: "{{ item }}"
      dest: /var/www/html/
    with_items:
      - templates/ansible-tower-small.png
...